---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rackoptix-db-pvc
  namespace: rackoptix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rackoptix-db
  namespace: rackoptix
  labels:
    app: rackoptix
    component: database
spec:
  serviceName: rackoptix-db
  replicas: 1
  selector:
    matchLabels:
      app: rackoptix
      component: database
  template:
    metadata:
      labels:
        app: rackoptix
        component: database
    spec:
      containers:
      - name: postgres
        image: postgis/postgis:14-3.2
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: rackoptix-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: rackoptix-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rackoptix-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - rackoptix
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - rackoptix
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: init-scripts
        configMap:
          name: rackoptix-db-init-scripts
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: rackoptix-db
  namespace: rackoptix
  labels:
    app: rackoptix
    component: database
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: rackoptix
    component: database
  clusterIP: None  # Headless service for StatefulSet

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rackoptix-db-init-scripts
  namespace: rackoptix
data:
  01-schema.sql: |
    -- This will be replaced with the actual schema.sql content
    CREATE EXTENSION IF NOT EXISTS postgis;
    
    -- Create tables and other schema objects
    -- This is a placeholder and should be replaced with the actual schema

  02-seed.sql: |
    -- This will be replaced with the actual seed.sql content
    -- Insert initial data
    -- This is a placeholder and should be replaced with the actual seed data