apiVersion: v1
kind: Secret
metadata:
  name: rackoptix-secrets
  namespace: rackoptix
type: Opaque
data:
  # These values are base64 encoded
  # In a real environment, these would be managed by a secrets management system
  # and not stored in version control
  POSTGRES_USER: cmFja29wdGl4  # rackoptix
  POSTGRES_PASSWORD: cmFja29wdGl4X3Bhc3N3b3Jk  # rackoptix_password
  
  # API keys and other sensitive information
  JWT_SECRET: c2VjcmV0X2tleV9mb3JfandfdG9rZW5z  # secret_key_for_jw_tokens
  
  # Database connection string (includes credentials)
  DATABASE_URL: cG9zdGdyZXM6Ly9yYWNrb3B0aXg6cmFja29wdGl4X3Bhc3N3b3JkQHJhY2tvcHRpeC1kYjo1NDMyL3JhY2tvcHRpeA==  # postgres://rackoptix:rackoptix_password@rackoptix-db:5432/rackoptix